### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by geoplayx** [elehobica/rasp_pi_pico_sine_wave_i2s_32bit#3]
Hi! Can you make a .uf2 file of this and also the pico i2s headphone project?.thank you

**Comment by elehobica** [comment]
Hi @geoplayx 
I made a release with binary.
I'm not for sure about `pico i2s headphone` project, but if you mean https://github.com/elehobica/pico_spdif_dac_hpamp, I did as well.

**Comment by geoplayx** [comment]
Yes, Thank you very much you also included this
https://github.com/elehobica/pico_spdif_dac_hpamp
Have a nice day!
